### PR TITLE
Allow forced encoding option

### PR DESCRIPTION
**Pull request by Carrington**
Nokogiri allows the consumer to pass in an optional declaration of which encoding it should try to force a document into, which allows the user to get around bad encoding declarations on external sources. This PR suggests adding an additional, optional parameter to Parser's constructor as a means to thread that option through to Nokogiri.

### CODE REVIEW

**Comment by jbielick** [comment]
bump: Need this ability. @szajbus could you take a look?

**Comment by szajbus** [comment]
@Carrington Thanks for the patch.

This is a useful option. However I think that setting a hard dependency on a specific nokogiri version is going to make it difficult to use this gem for some people.

I updated the test configuration in `master` branch, so that ruby versions 1.9 and 2.0 are now tested with nokogiri 1.6, so this should not be a problem anymore and we can get away without tightening that dependency.

Can you please revert the last commit and rebase on master? I will merge right away.

Cheers!

**Comment by Carrington** [comment]
:+1: @szajbus thanks for the help, done and done!

**Comment by szajbus** [comment]
@Carrington @jbielick Pushed version `0.5.2` to rubygems 💎💎💎

**Comment by jbielick** [comment]
Many thanks!

**Pull request merged**
